### ISSUE TITLE
Can you elaborate on the special features of ranges?

### ISSUE THREAD

**Issue by yvwmash** [think-cell/range#27]
Sorry, but from the ranges example I do not get what is so special about your addendums. I have a feel that these `_break` and `_continue` is something new. But the goal that the example pursues is eluding me. 

Maybe for the person who watches closely about what is the situation with the standard, it is all clear. But I feel that the example is too simple to show the area of problems that these new ranges do cover.

The very first google search about the explanation what these ranges do mean, got me to the example somewhat similar to your example. Maybe it is also a post from the author(s)? Anyway, iterating through, or getting of, or differentiating on even/odd numbers could be done with less text per page even in C++98/C89. What is so special about the ranges?

I understand that seeking for easy solutions is not a path of a true library maintainer. Still, coming from C programming I see the example as overkill.

**Comment by schoedl** [comment]
C++ ranges support iteration via iterators, typically called external iteration. think-cell ranges also support internal iteration, passing the elements into a sink. This can be easier to implement and sometimes more efficient. You essentially implement for_each for the range, receiving a sink and calling the sink with each element. To control when to stop, the sink can return tc::break_.

The nice think is that you can use the same adaptors, like tc::filter or transform on these ranges as on ranges supporting only iterators. The client typically doesn’t care what kind of iteration is used internally.


--
Dr. Arno Schoedl
CTO
***@***.******@***.***> | +49 30 6664731-0

think-cell Software GmbH (Web site<https://www.think-cell.com>)
Leipziger Str. 51, 10117 Berlin, Germany
Main phone +49 30 6664731-0 | US toll-free +1 800 891 8091

Amtsgericht Berlin-Charlottenburg HRB 180042 | European Union VAT Id DE308385481
Directors: Alexander von Fritsch, Christoph Hobo

Please refer to our privacy policy<https://www.think-cell.com/privacy> on how we protect your personal data.

On 19. Oct 2024, at 13:39, Ярослав Машко ***@***.***> wrote:

﻿

Sorry, but from the ranges example I do not get what is so special about your addendums. I have a feel that these _break and _continue is something new. But the goal that the example pursues is eluding me.

Maybe for the person who watches closely about what is the situation with the standard, it is all clear. But I feel that the example is too simple to show the area of problems that these new ranges do cover.

**Comment by yvwmash** [comment]
I've sketched a quick test for ranges. I do not see that your example use a "|", pipe operator, so I left the test for tc::ranges for some time later.

===
C++, g++ (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0
g++ -std=c++23 -O3 prob0.cpp -o prob0
```
#include <limits.h> 
#include <iostream> 
#include <ranges> 
#include <vector> 
  
int main(int argc, char *argv[]) 
{
 (void)argc;
 (void)argv;

 std::vector<int> nums = {};
 nums.reserve(INT_MAX);

 for(unsigned i = 0; i < INT_MAX; ++i) {
  nums.emplace_back(i);
 }

    auto even_nums = nums | std::views::filter([](int n) { 
                         return n % 2 == 0; 
                     });

    for (auto num : even_nums) { 
        if(num % 2 != 0)
		 return 1;
    }

 return 0;
}
```

C++, 28 lines, longer lines, harder to grasp
consecutive executions, digits stay mostly the same
```
	Command being timed: "./prob0"
	User time (seconds): 2.19
	System time (seconds): 1.59
	Percent of CPU this job got: 99%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:03.79
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 8391468
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 2097286
	Voluntary context switches: 1
	Involuntary context switches: 22
	Swaps: 0
	File system inputs: 0
	File system outputs: 0
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0
```

**Comment by yvwmash** [comment]
===
C, 33 lines, shorter lines, easier to grasp
consecutive executions, digits stay mostly the same
gcc (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0
gcc -std=c2x -O3 prob0.c -o prob0c
```
#include <limits.h> 
#include <stdlib.h> 
  
int main(int argc, char *argv[]) 
{
 (void)argc;
 (void)argv;

 int *nums, *even_nums;
 nums = malloc(INT_MAX * sizeof(int));
 even_nums = malloc(INT_MAX * sizeof(int) / 2 + 1);

 for(unsigned i = 0; i < INT_MAX; ++i) {
  nums[i] = i;
 }

 unsigned eveni = 0;
 unsigned num;
 for(unsigned i = 0; i < INT_MAX; ++i) {
  num = nums[i];
  if(num == 0) {
   even_nums[eveni] = num;
   eveni += 1;
  }
 }

 for (unsigned i = 0; i < eveni;  i += 1) { 
     if(even_nums[i] % 2 != 0)
		 return 1;
    }

 return 0;
}
```

```
	Command being timed: "./prob0c"
	User time (seconds): 1.07
	System time (seconds): 1.58
	Percent of CPU this job got: 99%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:02.65
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 8389884
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 2097220
	Voluntary context switches: 1
	Involuntary context switches: 11
	Swaps: 0
	File system inputs: 0
	File system outputs: 0
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0
```

**Comment by schoedl** [comment]
Then keep using C.

Arno


--
Dr. Arno Schoedl
CTO
***@***.******@***.***> | +49 30 6664731-0

think-cell Software GmbH (Web site<https://www.think-cell.com>)
Leipziger Str. 51, 10117 Berlin, Germany
Main phone +49 30 6664731-0 | US toll-free +1 800 891 8091

Amtsgericht Berlin-Charlottenburg HRB 180042 | European Union VAT Id DE308385481
Directors: Alexander von Fritsch, Christoph Hobo

Please refer to our privacy policy<https://www.think-cell.com/privacy> on how we protect your personal data.

On 19. Oct 2024, at 18:03, Ярослав Машко ***@***.***> wrote:

﻿

===
C, 33 lines, shorter lines, easier to grasp
consecutive executions, digits stay mostly the same
gcc (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0

#include <limits.h>
#include <stdlib.h>

int main(int argc, char *argv[])
{
 (void)argc;
 (void)argv;

 int *nums, *even_nums;
 nums = malloc(INT_MAX * sizeof(int));
 even_nums = malloc(INT_MAX * sizeof(int) / 2 + 1);

 for(unsigned i = 0; i < INT_MAX; ++i) {
  nums[i] = i;
 }

 unsigned eveni = 0;
 unsigned num;
 for(unsigned i = 0; i < INT_MAX; ++i) {
  num = nums[i];
  if(num == 0) {
   even_nums[eveni] = num;
   eveni += 1;
  }
 }

 for (unsigned i = 0; i < eveni;  i += 1) {
     if(even_nums[i] % 2 != 0)
                 return 1;
    }

 return 0;
}


        Command being timed: "./prob0c"
        User time (seconds): 1.07
        System time (seconds): 1.58
        Percent of CPU this job got: 99%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:02.65
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 8389884
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 0
        Minor (reclaiming a frame) page faults: 2097220
        Voluntary context switches: 1
        Involuntary context switches: 11
        Swaps: 0
        File system inputs: 0
        File system outputs: 0
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0
