### ISSUE TITLE
msvc tool chain support

### ISSUE THREAD

**Issue by frederich** [think-cell/range#4]
The commit 262fb81a21f55a03f998b404f8fa7652595e18fd drops CL compiler support, why?

**Comment by treh** [comment]
The range library still supports the msvc tool chain.
Actually, we use it ourselves with Visual Studio 2015.

**Comment by frederich** [comment]
Hello @treh, I was too imprecise. The range cmake example project doesn't work with VS. You dropped the cmake msvc compiler settings. Furthermore the 262fb81a21f55a03f998b404f8fa7652595e18fd drops VS 2013 support.

I still use the range library with VS 2013. It has work fine, until commit 262fb81a21f55a03f998b404f8fa7652595e18fd. Not every user can use the newest VS version. For instance: I cannot upgrade to VS 2015, I use it in combination with Windows Embedded Compact 2013 where the platform builder requires VS 2013.
